baseurl = "https://TheReserveForce.com/"
title = "The Reserve Force"
author = "Ricardo N Feliciano (FelicianoTech)"
canonifyurls = true
paginate = 3

theme = "hugo-theme-lean-launch-page"

googleAnalytics = "UA-129409801-1"

[params]
tagline = "Resources for U.S. Military reservists. Coming soon."
mailchimpURL = "//TheReserveForce.us19.list-manage.com/subscribe/post?u=7d0785042c911451e8e716e3b&amp;id=d42254f9f5"

twitter = "https://twitter.com/TheReserveForce"
facebook = "https://facebook.com/MyNewProduct"
